### ISSUE TITLE
vendor:publish don't create the config/breadcrmbs.php

### ISSUE THREAD

**Issue by boomhq** [davejamesmiller/laravel-breadcrumbs#160] opened 2018-01-10 13:47 UTC
Hello guys,
Thanks for your wonderfull project.
I use it for the first time on laravel 5.5 and i have an issue.
When i type` php artisan vendor:publish --provider='DaveJamesMiller\Breadcrumbs\BreadcrumbsServiceProvider'
`
No file published in config/.

Thanks by advance

**Comment by davejamesmiller** [comment] 2018-01-11 12:08
Works for me.

```bash
$ composer create-project --prefer-dist laravel/laravel lb-test
Installing laravel/laravel (v5.5.28)

$ cd lb-test/

$ composer require davejamesmiller/laravel-breadcrumbs
Using version ^4.2 for davejamesmiller/laravel-breadcrumbs

$ php artisan vendor:publish --provider='DaveJamesMiller\Breadcrumbs\BreadcrumbsServiceProvider'
Copied File [/vendor/davejamesmiller/laravel-breadcrumbs/config/breadcrumbs.php] To [/config/breadcrumbs.php]
Publishing complete.

$ ls config/
app.php  auth.php  breadcrumbs.php  broadcasting.php  cache.php  database.php  filesystems.php  mail.php  queue.php  services.php  session.php  view.php
```

Closing as not a bug - but if you can come up with a reproducible case where it happens let me know and I can re-open it.

**Closed by davejamesmiller** 2018-01-11 12:08 UTC

**Comment by arturmamedov** [comment] 2018-02-15 08:58
Same on `4.2.0` try to update and let you know

**Comment by codesticle** [comment] 2018-03-06 16:01
Same issue on version 5. My setup is:

Laravel 5.6
Windows with XAMPP
Running Composer from Windows Command Line

I was able to get around it by manually copying the config file from /vendor/davejamesmiller/laravel-breadcrumbs/config/breadcrumbs.php

**Comment by davejamesmiller** [comment] 2018-03-06 16:12
I don't use Windows - so maybe it's a Windows issue?

If one of you can confirm that, fix it and open a PR then I'll merge it.

**Comment by nruslan** [comment] 2018-04-28 16:15
Since I am developing on Windows environment I had the same issue. The file didn't publish. The solution is simple. You need to use double quotes.
`php artisan vendor:publish --provider="DaveJamesMiller\Breadcrumbs\BreadcrumbsServiceProvider"`
